#! /usr/bin/env bash

# shellcheck source=/dev/null
# shellcheck disable=SC2034

host_main_() {
  hostname="$(basename "$0")"
  auto_update_type="default"

  source "$PWD"/../roles/workstation
}

host_main_